### ISSUE TITLE
Question UI

### ISSUE THREAD

**Issue by GurkeTonic** [pvyParts/allianceauth-corpstats-two#19]
Are there any plans to convert the module to the new Auth UI?

**Comment by soratidus999** [comment]
Auth reports is essentially AA-corpstats-three 

https://github.com/Solar-Helix-Independent-Transport/allianceauth-auth-reports

Auth reports is still in development

**Comment by GurkeTonic** [comment]
Ah, so Corpstats-two will not be developed further? Too bad, we don't use Auth-Report :(

The function to see if the members have connected to the services and which chars are still missing in the auth is great for the needs of the alliance

**Comment by soratidus999** [comment]
Yes, auth reports is planned to be a complete replacement, including the features you've mentioned.

It is just more flexible and allows people to build out the data thats relevant to them
