### ISSUE TITLE
Permissions don't seem to work

### ISSUE THREAD

**Issue by ppfeufer** [pvyParts/allianceauth-corpstats-two#2]
`can view corpstats` and `can view corp stats of their own corporation` don't seem to work.

Both are set for a group and the user in said group doesn't see the corp stats menu.

![Selection_244](https://user-images.githubusercontent.com/2989985/71647097-e0e3fe00-2cf1-11ea-9adc-5046979f6d0e.jpg)

![](https://cdn.discordapp.com/attachments/438459192634900484/662065496778342400/unknown.png)

**Comment by pvyParts** [comment]
Should be fixed in 1.0.3, if not feel free to re-open
