### ISSUE TITLE
[QoL] Add numeric values to service actiivation stats

### ISSUE THREAD

**Issue by ppfeufer** [pvyParts/allianceauth-corpstats-two#5]
Percentage values are great but adding numeric values would add even more information without the need to do some quick maths .-)

Thinking about something like this

![540f10aaa716](https://user-images.githubusercontent.com/2989985/87711926-3ff9f380-c7a8-11ea-8b63-0d2c1bca3418.jpg)

**Comment by pvyParts** [comment]
Added ill push a new version some time today

![Imgur](https://i.imgur.com/mJDy3A2.png)

**Comment by ppfeufer** [comment]
Thank you for implementing this!
